### ISSUE TITLE
Flask host parameter

### ISSUE THREAD

**Issue by frakev** [aldevar/zabbix-db-migration#3]
Maybe, we can use the host parameter in app.run() to get automatically the IP address.
Currently, the script is listening only on 127.0.0.1.

**Example:**

```python
import socket

def _getIpAddress():
         return socket.gethostbyname(socket.gethostname())

...

if __name__ == "__main__":
    app.run(debug=True, host=_getIpAddress())
```

**Comment by n0xas69** [comment]
Yes good idea,

and next time i will add the the automatic browser opening when the user launch "app.py"

**Comment by frakev** [comment]
Modifications pushed to frakev branch.
